import OpenAI from 'openai';
import dotenv from 'dotenv';

dotenv.config();

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function generateSummary(description: string): Promise<string> {
  const completion = await openai.chat.completions.create({
    model: 'gpt-3.5-turbo',
    messages: [
      {
        role: 'system',
        content: 'You summarize incident reports for a senior care home.',
      },
      {
        role: 'user',
        content: `Staff at a senior care home reported an incident with description. Summarize this incident regarding a senior citizen  and give key insights to why this could have happened: ${description}`,
      },
    ],
  });

  const message = completion.choices[0]?.message?.content;
  if (!message) throw new Error('No summary was generated by OpenAI.');

  return message.trim();
}
